// This file is auto-generated by @hey-api/openapi-ts

export type AccessToken = {
    token?: string | null;
    expiresAt?: string;
};

export type AuthRequest = {
    initData?: string | null;
    referralCode?: string | null;
};

export type GameLookup = {
    id?: number;
    pigsCollected?: number;
    createdAt?: string;
    validTill?: string;
    nextGameAvailableAt?: string;
};

export type PigsRecordDto = {
    maxPigsAmount?: number;
};

export type ScoreboardPagedList = {
    items?: Array<ScoreboardUser> | null;
    totalItems?: number;
    totalActivePlayers?: number;
};

export type ScoreboardUser = {
    id?: number;
    username?: string | null;
    pigsAmount?: number;
    ticketsAmount?: number;
    referrals?: number;
};

export type UpdateUserDto = {
    treasuryUpdatedPopupShown?: boolean | null;
    newRecordPopupShown?: boolean | null;
    newGlobalRecordPopupShown?: boolean | null;
};

export type UserDescription = {
    id?: number;
    telegramId?: number;
    username?: string | null;
    scoreboardPosition?: number;
    pigsAmount?: number;
    maxPigsAmount?: number;
    ticketsAmount?: number;
    referrals?: number;
    referralCode?: string | null;
    treasuryUpdatedPopupShown?: boolean;
    newRecordPopupShown?: boolean;
    newGlobalRecordPopupShown?: boolean;
};

export type PostApiAuthData = {
    body?: AuthRequest;
    path?: never;
    query?: never;
    url: '/api/Auth';
};

export type PostApiAuthResponses = {
    /**
     * Success
     */
    200: AccessToken;
};

export type PostApiAuthResponse = PostApiAuthResponses[keyof PostApiAuthResponses];

export type GetApiGameLatestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Game/latest';
};

export type GetApiGameLatestResponses = {
    /**
     * Success
     */
    200: GameLookup;
};

export type GetApiGameLatestResponse = GetApiGameLatestResponses[keyof GetApiGameLatestResponses];

export type GetApiTreasuryBalanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Treasury/balance';
};

export type GetApiTreasuryBalanceResponses = {
    /**
     * Success
     */
    200: number;
};

export type GetApiTreasuryBalanceResponse = GetApiTreasuryBalanceResponses[keyof GetApiTreasuryBalanceResponses];

export type PostApiTreasuryResetNotificationsData = {
    body?: never;
    headers?: {
        apiKey?: string;
    };
    path?: never;
    query?: never;
    url: '/api/Treasury/reset-notifications';
};

export type PostApiTreasuryResetNotificationsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiUserScoreboardData = {
    body?: never;
    path?: never;
    query?: {
        Limit?: number;
        Offset?: number;
    };
    url: '/api/User/scoreboard';
};

export type GetApiUserScoreboardResponses = {
    /**
     * Success
     */
    200: ScoreboardPagedList;
};

export type GetApiUserScoreboardResponse = GetApiUserScoreboardResponses[keyof GetApiUserScoreboardResponses];

export type GetApiUserPigsRecordData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/User/pigs-record';
};

export type GetApiUserPigsRecordResponses = {
    /**
     * Success
     */
    200: PigsRecordDto;
};

export type GetApiUserPigsRecordResponse = GetApiUserPigsRecordResponses[keyof GetApiUserPigsRecordResponses];

export type GetApiUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/User';
};

export type GetApiUserResponses = {
    /**
     * Success
     */
    200: UserDescription;
};

export type GetApiUserResponse = GetApiUserResponses[keyof GetApiUserResponses];

export type PutApiUserData = {
    body?: UpdateUserDto;
    path?: never;
    query?: never;
    url: '/api/User';
};

export type PutApiUserResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'https://devgame.piggyhodl.xyz' | (string & {});
};